[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-cloud.txt"
]

[phases.build]
cmds = ["mkdir -p storage/{photos,reports,temp}"]

[start]
cmd = "python start.py"