services:
  - type: web
    name: inventory-ai
    runtime: docker
    dockerfilePath: ./docker/Dockerfile.render
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: API_KEY
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: APP_TIMEZONE
        value: America/Los_Angeles
      - key: USE_PADDLE_OCR
        value: "false"
      - key: STAGING_BINS
        value: S-01,S-02,S-03,S-04
      - key: STAGING_THRESHOLD_HOURS
        value: "12"
      - key: STORAGE_BACKEND
        value: local
      - key: STORAGE_LOCAL_DIR
        value: /app/storage
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - docker/**
        - requirements-render.txt
        - .env.example

databases:
  - name: inventory-db
    databaseName: inventory_ai
    plan: starter
    postgresMajorVersion: 15
